### ISSUE TITLE
some Cookies not marked as ‘Secure’ 

### ISSUE THREAD

**Issue by rahul-kumar11** [subrata1106/TestRel17.2#31]
https://oxfordlearn.mantishub.com/view.php?id=3857

**Comment by rahul-kumar11** [comment]
IV.	OUP-cookie
V.	EAC-ERIGHTS
VI.	.ASPXAUTH
VII.	WT_FPC
VIII.	AdminJoiningCodeTab – Distributed joining code-> Manage Organization
IX.	Countrytabs_ID – Manage users-> Edit user detail-> Transaction

**Comment by JB-PATEL** [comment]
This is fixed. Pls check. Cookies only being created by the system will be secure not ALL.
Please check accordingly.

**Comment by JB-PATEL** [comment]
webtrebds url is http hence we can not mark the cookie as secured.

http://statse.webtrendslive.com/dcs1wov9k00000shsztaa1oay_3j9q/wtid.js?callback=Webtrends.dcss.dcsobj_0.dcsGetIdCallback

**Comment by rahul-kumar11** [comment]
Some of the Cookies are still not secured. So I will not close the issue.
